export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const INGREDIENTS_ERROR = "INGREDIENTS_ERROR";

export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START"
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_ERROR = "PURCHASE_BURGER_ERROR";
export const PURCHASE_INIT = "PURCHASE_INIT"; 